### PR TITLE
Move remote setup in ray stream executor to enable configuration

### PR DESCRIPTION
**Pull request by amitschang**
Setting up remotes in the initialization meant that task specific overrides like setting num_cpus via executor set_config did not have affect.

Resolves https://github.com/ssec-jhu/dplutils/issues/67

### CODE REVIEW

**Comment by ryanhausen** [comment]
@amitschang thanks, will review

**Comment by amitschang** [comment]
@ryanhausen, thanks, you are more than welcome to of course, but I did switch the automated request to Xiang since he's using this package.

**Comment by xiangchenjhu** [comment]
> Setting up remotes in the initialization meant that task specific overrides like setting num_cpus via executor set_config did not have affect.

How to set num_cpus in this scenario?

**Comment by amitschang** [comment]
@xiangchenjhu , can you be more specific? The test shows how this could be done, and from the command line it would be like 
```
pl --set-config task.num_cpus=2
```

**Review by xiangchenjhu — APPROVED** [review]
After reviewing the logic for advancing resource splitting into the initialization stage and conducting tests, it looks good

**Pull request merged**
