### PR TITLE
Restoring codecov action

### PR DESCRIPTION
**Pull request by amitschang**

### CODE REVIEW

**Review by jamienoss — CHANGES_REQUESTED** [review]
``tox.ini`` needs to be updated to produce xml for codecov, either instead of or as well as.
https://github.com/ssec-jhu/dplutils/blob/main/tox.ini#L32
```yaml
pytest --cov --cov-report=xml:coverage.xml {posargs}
```

**Comment by amitschang** [comment]
@jamienoss, thanks! I thought we had that already by default (and seems we do in base-template). Perhaps though we should just always do both html and xml

**Comment by jamienoss** [comment]
base-template useses xml https://github.com/ssec-jhu/base-template/blob/main/tox.ini#L30
I'm down for using both as html is better for viewing
 local reports.
In the very beginning, it was both, but I seem to remember something not working though...

**Comment by amitschang** [comment]
@jamienoss , not sure. This change that contains both looks like it works both locally and with codecov. Also, note that the doc thing is expected to fail, but fix is already in the pipe in #8

**Review by jamienoss — APPROVED** [review]

**Pull request merged**
